### PR TITLE
allow disabling outlier detection

### PR DESCRIPTION
**Pull request by mbektasbbg**

### CODE REVIEW

**Comment by kaiayoung** [comment]
@mbektasbbg `BoxPlotModel.js` will also need to be updated with the new `auto_detect_outliers` attribute. LGTM, aside from that!

**Comment by mbektasbbg** [comment]
@kaiayoung thanks, I forgot to do so again :) will push an update.

**Comment by mbektasbbg** [comment]
@SylvainCorlay can you take a look?

**Comment by SylvainCorlay** [comment]
Sorry I missed it!

**Pull request merged**
