### PR TITLE
bqplot 0.12.3, npm package 0.5.3

### PR DESCRIPTION
**Pull request by jasongrout**
This is the tagged published release commit for bqplot 0.12.3, npm package 0.5.3.

dist/bqplot-0.12.3-py2.py3-none-any.whl
md5: e0829197d0287783f30419a56d210814
sha1: c33cd72452c0035f194293bde5fa855d87d55f51
sha256: b1b9664c4faaae91ec3773b1083bfa97108a4d6556109afed2ebaeab8c5c83b6

dist/bqplot-0.12.3.tar.gz
md5: 78520772cc1aa7770bcf02eaadf81541
sha1: 7e262468ff2189b3de397b86315e63206a213337
sha256: 7292b57694ebe8347e48e16bd47449bbd886f9c2c238b744ed59871960451b59

CC @kaiayoung

### CODE REVIEW

**Comment by martinRenou** [comment]
Are we not taking care of the PRs mentioned here #999 before making the release?
There are lots of bug fixes.

**Comment by jasongrout** [comment]
> Are we not taking care of the PRs mentioned here #999 before making the release?
> There are lots of bug fixes.

Good point. I guess what is left can be in an 0.12.4, since the release already happened. I'll comment over there.

**Comment by SylvainCorlay** [comment]
@jasongrout you need to sign off your last commit for this to be merged.

**Comment by jasongrout** [comment]
> @jasongrout you need to sign off your last commit for this to be merged.

Thanks. Done.

**Comment by SylvainCorlay** [comment]
@jasongrout I am confused at what should be the process for releases when we cannot push to master and release commits are in PRs.

Should we avoid merging other PRs before this one (so that it remains basically fast-forward?)

**Comment by jasongrout** [comment]
Yes, I don't have a good idea for what to do either. Thanks for trying to make it easy by holding off merging while we figure it out.

**Pull request merged**
