### PR TITLE
Pep8 cleanup

### PR DESCRIPTION
**Pull request by ChakriCherukuri**
1. Fixed PEP8 warnings in the python files
2. Tested to make sure all the example notebooks are running fine

### CODE REVIEW

**Comment by dmadeka** [comment]
Looks like the commit history is pretty broken here

**Comment by kaiayoung** [comment]
LGTM, reviewed as requested by Chakri

**Comment by jasongrout** [comment]
> Looks like the commit history is pretty broken here

Can you elaborate, @dmadeka? It looks like each commit is fixing pep8 warnings in a different file.

**Comment by dmadeka** [comment]
@jasongrout Yup, but they're all titled the same. So it looks like 10 straight commits of the same name, which isnt very informative. It might make sense to add more details to the commit names, or squashing them into a single comment

**Pull request merged**
