### PR TITLE
HeatMap

### PR DESCRIPTION
**Pull request by rmenegaux**
Basic HeatMap mark, that plots 2d `color` data against 1d `x` and `y`.

`HeatMap` uses canvas to draw a rectangle of color `color_{i,j}` "centered" around each point of coordinates `(x_i, y_j)`

It can be used as an Image mark too.

### CODE REVIEW

**Comment by dmadeka** [comment]
GridHeatMap and HeatMap? Can you detail this PR more?

**Comment by rmenegaux** [comment]
@dmadeka `HeatMap` is to be used when there is too much data for the `GridHeatMap`. The latter makes every cell a DOM element, which is certainly good for interactivity and flexibility, but will crash the browser if there are too many cells.
`HeatMap` uses canvas to draw the cells, which allows for a much greater number of elements. This is at the expense, however, of the interactivity of svg, and as of now I have not coded in the tooltip and other interactions.
It is still WIP as there are some padding issues I need to fix.

**Comment by dmadeka** [comment]
Can we call it `Image` ala mpl?

**Comment by dmadeka** [comment]
also, would be cool to be able to do this:

http://bl.ocks.org/mbostock/b75883984a032ea0ba26

**Comment by dmadeka** [comment]
@rmenegaux Still a WIP?

**Comment by rmenegaux** [comment]
This works fine as far as I can see. I just haven't figured out a good way to do the padding yet. As of now it has none.

**Comment by dmadeka** [comment]
@rmenegaux Can you open an issue?

**Comment by dmadeka** [comment]
@rmenegaux Can you add a documented example notebook?

**Comment by rmenegaux** [comment]
:+1:

**Pull request merged**
