### PR TITLE
[WIP] Image mark

### PR DESCRIPTION
**Pull request by izaid**
This is a massive work in progress, but I've got some basic things working so far. More soon.

### CODE REVIEW

**Comment by izaid** [comment]
The NdArray trait is too slow for images, by the way. We need to update the _to_json method to pass the data as bytes in a field.

For now, I can pass the bytes directly as a unicode trait, just like Jupyter does.

**Comment by SylvainCorlay** [comment]
Woot! Thanks for starting this!

Regarding the NdArray, there is a buffer attribute in the comm protocol that we can use for binary data. We should move to that eventually.

**Comment by izaid** [comment]
Okay, so this is a very basic Image mark that now works. I've even added an example notebook at "Image.pynb". Obviously, there is a lot more to do here. The limitation really is the JSON serialization, as I mentioned above. I think we should merge this if @SylvainCorlay is happy, then I'd like fix the JSON serialization, come back, and make this much better.

@SylvainCorlay Are you happy with what I've done so far? If not, can you give me comments on what you'd like changed?

Right now, the image has to be set with a binary data source, which is weird but at least it works. We'll change it to an NdArray once the JSON problem is resolved.

**Comment by dmadeka** [comment]
@izaid I noticed nothing was changed in any of notebooks apart from `Image.ipynb`. Can you remove them from the PR?

**Comment by izaid** [comment]
@dmadeka Yeah, sure, I'll make sure they are all removed before we merge. What I'd really like to know is what more you would like before you consider this "mergable". Again, my goal here is to get a basic Image mark in, fix up other stuff, then come back.

**Comment by SylvainCorlay** [comment]
Hi all I can look into this and specifically the binary serialization
tomorrow morning.
Sylvain

**Comment by dmadeka** [comment]
Why don't we discuss on the [gitter](https://gitter.im/bloomberg/bqplot)?

**Comment by SylvainCorlay** [comment]
I am not available at the moment.

**Comment by izaid** [comment]
Closing this, will reopen shortly.

**Pull request closed without merging**
