### PR TITLE
Remove explicit jquery dependency

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Using native DOM apis in Toolbar.js

### CODE REVIEW

**Comment by dmadeka** [comment]
I can test this, but let's not merge till that's done

**Comment by SylvainCorlay** [comment]
👍

**Comment by SylvainCorlay** [comment]
arg, the output_area_resize is an event baked in for the fullscreen hack.

**Comment by dmadeka** [comment]
Along with the triple update_layout functions I believe

**Comment by SylvainCorlay** [comment]
triple?

**Comment by dmadeka** [comment]
```JavaScript
    update_layout: function() {
    update_layout2: function() {
    update_layout3: function() {
```

**Comment by SylvainCorlay** [comment]
ok I see what you mean. The `update_layout` functions are required regardless of the resize event.

**Comment by SylvainCorlay** [comment]
Ready for review. Not removing the `output_area_resize` for now, because it is coupled with bqnb. This will not be required anymore when we release ipywidgets 6.0 which will have the phosphor resize events.

**Pull request closed without merging**
