### PR TITLE
Move Index to Site Map

### PR DESCRIPTION
**Pull request by dmadeka**
@madridnick @SylvainCorlay This is a move to remove the confusion created by the Index name. Ive moved Sylvain's talk to the Introduction. This also helps because, the display of the YouTube video needs the cell to be run, which the structure of `Index.ipynb` didn't lend to, but `Introduction.ipynb` does.

Im open to other suggestions as well.

### CODE REVIEW

**Comment by madridnick** [comment]
LGTM

**Comment by SylvainCorlay** [comment]
what was the confusion about `Index.ipynb`?

**Comment by dmadeka** [comment]
@SylvainCorlay Just that its not consistent with other docs, I do like `Site Map`. Is there any reason we should keep `Index`, like binder etc?

**Comment by SylvainCorlay** [comment]
@madridnick @dmadeka I think that we should keep the `index.ipynb` name for the entry point. This is the current convention for the mybinder project, and will therefore become the expected entry point.

**Pull request closed without merging**
