### PR TITLE
Figure as a tooltip for MarketMap doesn't display

### PR DESCRIPTION
**Pull request by ssunkara1**
Triggering `displayed` so that the size of the `Figure` is set.

### CODE REVIEW

**Comment by jasongrout** [comment]
The market map example notebook last cell works fine for me with #371. Can you check on that PR? If it works for you, I'm curious why it works without this line.

**Comment by ssunkara1** [comment]
I think it is because of lines 107 and 108 in `Figure.js` where the min-width and min-height of the svg are being added. Yesterday after a discussion with @SylvainCorlay I removed them in #370

**Comment by jasongrout** [comment]
No, the min-width and min-height of the *svg* are there now so that the enclosing Figure div has a natural size. Otherwise we were getting the enclosing div to be zero-sized.

**Comment by jasongrout** [comment]
Which I guess is about what you said.

**Comment by ssunkara1** [comment]
@jasongrout This is good to merge :)

**Comment by jasongrout** [comment]
Great, thanks!

**Pull request merged**
