### PR TITLE
Finish converting to es6 classes

### PR DESCRIPTION
**Pull request by jasongrout**
I think this finishes out the conversion to es6 classes.

### CODE REVIEW

**Comment by jasongrout** [comment]
This fixes the test compile errors, but it only "passes" by skipping most tests. I'll open an issue to fix the tests.

**Comment by JohanMabille** [comment]
LGTM.
I have a question regarding `styles` from`d3-selection-multi`, do you know why it still works even if not importing `d3-selection-multi` ? Did I miss something?

**Comment by jasongrout** [comment]
So is this PR good?

**Comment by JohanMabille** [comment]
Yes, you can merge it. I have a PR ready for fixing the "styles" runtime error (I was just testing some notebooks befor opening it).

**Comment by jasongrout** [comment]
Great, thanks!

**Pull request merged**
