### PR TITLE
Pyplot adding order for compatible scales

### PR DESCRIPTION
**Pull request by ssunkara1**
This is an equivalent to PR #183 . This is for the master branch rather than for 0.5.x

### CODE REVIEW

**Comment by ssunkara1** [comment]
WIP is because I haven't tested this yet with Python 3.x. Will remove the WIP once I am done with that.

**Comment by ssunkara1** [comment]
@SylvainCorlay Right now, I can't get the jupyter notebook with python 3.x to display widgets. 

Can you check this when you have time? With this change, `pyplot.plot` should plot the graph with negative values. Previously, this was returning a `LogScale` which results in no graph being displayed.

**Comment by dmadeka** [comment]
@ssunkara1 Do you want me to take it from here?

**Comment by ssunkara1** [comment]
@SylvainCorlay can you confirm that there is no issue with the tabs in this pr? Thank you!!

**Comment by SylvainCorlay** [comment]
It seems to work. My 2c about the variable name:

what about `precedence`?

**Comment by ssunkara1** [comment]
@SylvainCorlay seems good. will change.

**Comment by dmadeka** [comment]
@SylvainCorlay Why not `preference`? So we can maintain the 1, 2, 3 order?

**Comment by ssunkara1** [comment]
@SylvainCorlay @dmadeka made the change to `preference`.

**Comment by ssunkara1** [comment]
@SylvainCorlay I am not convinced about `precedence`. I think, going forward, we will be adding scales which are of lower precedence than the ones we already have. So to avoid having to go to negative values, I think it is better to have a higher number for things of lower precedence.

Anyway I am ok with it either way since it is just a convention. I have a commit ready. You take the final call on this one.

**Pull request merged**
