### PR TITLE
fixing setup.py for windows

### PR DESCRIPTION
**Pull request by ssunkara1**
image

the `check_call` command works only for .exe files. .cmd files are not found by that unless the additional argument is passed and npm is not a .exe file. 

I checked that this works on windows and Ubuntu. Have not checked it on a mac.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks. Shell = True is a big security risk on unix systems. We should probably only do this on windows.

@jasongrout comments?

**Comment by ssunkara1** [comment]
I read that it is a risk if we are dynamically deciding the command to run directly from an external source. Since we are specifically running `npm` I do not think it is. But I do not know enough about this. :)

**Comment by SylvainCorlay** [comment]
Same here. It is a Pavlov reflex w.r.t. shell=True

**Comment by jasongrout** [comment]
See https://github.com/jupyter/jupyterlab/pull/144

**Comment by ssunkara1** [comment]
Thanks @jasongrout Updated the PR.

**Comment by SylvainCorlay** [comment]
@jasongrout we should do the same in 
 - pythreejs
 - ipyleaflet
 - widgetsnbextension
 - widget-cookiecutter
 - ipympl
 - nglview

**Comment by jasongrout** [comment]
Yep, agreed.

**Comment by jasongrout** [comment]
Perhaps we should make a standalone `npm.py` file in the same directory as `setup.py` that took care of common npm things?

**Pull request merged**
