### PR TITLE
explicitly say the install file is utf-8

### PR DESCRIPTION
**Pull request by jasongrout**
Attempts to address #36, though it's weird that it seems that we can happily encode the file to ascii.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
We might have to do this on all the file. In this PR, it could be interesting to do it in `__init__.py` as well since it is used to access `install.py`.

**Comment by SylvainCorlay** [comment]
@mjbright does this fix your issue with docker?

**Comment by mjbright** [comment]
Hi, sorry I've been travelling I did try without success but haven't been
able to spend more time investigating ... and probably won't for a month
now.

**Comment by SylvainCorlay** [comment]
This needs a rebase.

**Comment by SylvainCorlay** [comment]
I have searched for UTF chars and not found a single one so this should not be necessary.

**Comment by jasongrout** [comment]
Let's close this for now, then.

**Comment by jasongrout** [comment]
@mjbright - since this doesn't seem to fix the issue for you, I'm closing this.  Please let us know if you see this issue again and we'll try to help debug it better.

**Pull request closed without merging**
