### PR TITLE
Pie: Split draw function into sub-functions

### PR DESCRIPTION
**Pull request by martinRenou**
This also fixes issues with selected-style and font-style not being properly applied

### CODE REVIEW

**Comment by martinRenou** [comment]
This needs tests

**Comment by martinRenou** [comment]
Any chance we can merge this PR too?

**Comment by martinRenou** [comment]
I fixes an issue with `display_values` and some styling issues (selected and font)

**Comment by SylvainCorlay** [comment]
Will merge when #1035 is in.

**Comment by martinRenou** [comment]
Can this be merged? It fixes some issues with the Pie chart

**Pull request merged**
