### PR TITLE
Moved animate_dur attribute from marks to figure

### PR DESCRIPTION
**Pull request by ChakriCherukuri**
1. Moved animate_dur attribute from marks to figure. Since figure contains axis and multiple marks it makes sense for all of them to transition together.
2. Updated the example notebooks to reflect the above change
3. Fixed couple of bugs in Pie mark
4. Added a custom tween for Pie transitions

Note: Axis gridlines and ticks should also transition when individual marks transition. I am working on it and will create a separate PR for that.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
:+1: it could be a good time to rename this to `animate_duration`. We should figure out how to deprecate a trait attribute name.

**Comment by SylvainCorlay** [comment]
@ChakriCherukuri can you please also rebase?

**Comment by ChakriCherukuri** [comment]
Added the following changes - 
1. renamed "animate_dur" to "animation_duration" as per request of @SylvainCorlay 
2. enabled axis, gridlines and tick animations
3. Now enabling animations only on data updates (not when rendering plots)
4. added an example notebook which showcases animations of various marks on data updates
5. enabled animations (only on data updates) of non-positional data attributes of Scatter

@SylvainCorlay and @ssunkara1 please review (esp axis related changes)

**Comment by SylvainCorlay** [comment]
OK, I think this needs a simple rebase.

**Comment by ChakriCherukuri** [comment]
rebase done

**Comment by ssunkara1** [comment]
@ChakriCherukuri In the axis example, with the offset, the grid_lines do not go beyond the axis towards the negative numbers.

**Comment by ChakriCherukuri** [comment]
@ssunkara1 fixed the gridlines to go beyond the axis when offset is specified. Please review

**Comment by ssunkara1** [comment]
@ChakriCherukuri sorry for the delay. The change with the offset looks good. Thanks!

I just noticed a small bug. If I set the `grid_lines` to `solid` or `dashed` and then change them to `none`, the tick size still is the height or width of the figure. Hence there are solid lines in place of the grid lines.

Also, I think we should remove the string `'none'` and change it to a python `None`. Let me know what you think.

**Comment by ssunkara1** [comment]
@ChakriCherukuri Also, I noticed that the logic for animation in Lines and Hist is slightly different from the others. In these two, there is no explicit check for animate, which is present in the other marks. Any reason why they are different?

**Comment by SylvainCorlay** [comment]
Not sure about changing `'none'` to `None` since it would not be backward compatible.

**Comment by ChakriCherukuri** [comment]
@ssunkara1 Hist animations are tricky and currently the way they are done (each bar expanding in horizontal direction) is distracting and don't serve the purpose. I will do them later. For now it's better not to do Hist animations. Let me know if you think otherwise.

I will fix the gird lines bug. Thanks for letting me know.

I will also do the line animations (only on data updates)

**Comment by ChakriCherukuri** [comment]
@ssunkara1 Can you please check the axis issue we'd discussed today? Everything else looks good

**Comment by SylvainCorlay** [comment]
This is looking good to me. It is a true improvement. Unless @ssunkara1 does not comment or merge, I will merge soon.

**Comment by ChakriCherukuri** [comment]
@SylvainCorlay There's an issue with offsets which I and @ssunkara1 are looking into. Once we resolve it he will merge it.

**Comment by SylvainCorlay** [comment]
ok, let me know. I would like to push out a release before tomorrow's presentation, preferably with that PR in.

**Comment by ChakriCherukuri** [comment]
@SylvainCorlay since there are lot of changes it'd better you cut a release without this. I want to do more testing

**Comment by ChakriCherukuri** [comment]
@SylvainCorlay fixed all the issues. Can you also test on your end to see if everything looks good? Then we can merge

**Comment by SylvainCorlay** [comment]
The Animation notebook is great. Thanks.

**Pull request merged**
