### PR TITLE
new: Image mark has pixelated trait, to avoid interpolation

### PR DESCRIPTION
**Pull request by maartenbreddels**
For e.g. scientific plots, you want to see the pixels.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
This can probably followed up by an interpolation argument for imshow, I think 'none' or 'nearest' would be almost the same as this.

**Comment by rmenegaux** [comment]
@maartenbreddels cool! Should it default to `False` though? I'm not sure what the main use of the Image mark is.

**Comment by maartenbreddels** [comment]
mpl is now using it as default, so we may follow that: https://matplotlib.org/users/dflt_style_changes.html#interpolation
On top of that, it will by default show up if we have browser issues ;)

**Comment by maartenbreddels** [comment]
Another option is to use WebGL to draw the image onto a canvas with the same resolution as the screen, then we have much more control over the interpolation.

**Comment by maartenbreddels** [comment]
Replaced by https://github.com/bloomberg/bqplot/pull/630

**Pull request closed without merging**
