### PR TITLE
DOC: Fix a few Sphinx warnings

### PR DESCRIPTION
**Pull request by mgeier**
**Describe your changes**

Fixed a few Sphinx warnings.

**Testing performed**

Built the docs and the warnings are gone.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks @mgeier.

Unfortunately this repository requires to do `--signoff` on each ones of your commits...

Would you be ok with signing off the commit of your PRs so that we can merge?

**Comment by mgeier** [comment]
Sure, how can I do this?

**Comment by SylvainCorlay** [comment]
Basically, if you redo your commits with `-s` or `--signoff`, that should work.

**Comment by mgeier** [comment]
Better now?

**Comment by SylvainCorlay** [comment]
Thanks @mgeier ! Merging the PR.

**Pull request merged**
