### PR TITLE
Support `on_element_click` for `Image` mark

### PR DESCRIPTION
**Pull request by mwcraig**
This PR adds a custom message to handle image clicks. Unlike other marks, the data in this case is the location of the mouse click. Other marks like scatter return the coordinates of the data point; that doesn't make much sense to me for the case of the image mark.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thanks for the PR, I'll look into this in light of #630

**Comment by mwcraig** [comment]
Is there anything I should do to move this forward?

**Comment by mwcraig** [comment]
Friendly bump....would like to be able to get my click locations :)

**Comment by rmenegaux** [comment]
This looks good to me. Any thoughts @maartenbreddels ?

**Comment by mwcraig** [comment]
Another friendly bump.....

**Comment by rmenegaux** [comment]
Merging. Thanks @mwcraig

**Pull request merged**
