### PR TITLE
Fixup binder environment

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by dmadeka** [comment]
What about `setup.py`?

https://github.com/bloomberg/bqplot/blob/master/setup.py#L184

**Comment by SylvainCorlay** [comment]
These are the dependencies to run the example notebooks. bqplot does not actually depend on sklearn.

**Comment by dmadeka** [comment]
Does the pip install respect the dependencies in the yaml file?

**Comment by SylvainCorlay** [comment]
Not at all. The environmwnt.yml is a manisfest for the binder build

**Pull request merged**
