### PR TITLE
Color Scales

### PR DESCRIPTION
**Pull request by rmenegaux**
This addresses #384 and changes how color scales work. The new features are:
- The user can pass n colors, rather than just 2 or 3
screen shot 2018-02-05 at 22 04 48

- The linear color schemes are improved. We used to interpolate between the extreme colors (min/max or min/mid/max), now we use all the scheme's colors.
As an illustration, here are some colorbrewer schemes, before and after:

'Reds'
screen shot 2018-02-05 at 21 25 16
screen shot 2018-02-05 at 21 02 13

'Blues'
screen shot 2018-02-05 at 21 27 24
screen shot 2018-02-05 at 21 02 34

'RdYlGn'
screen shot 2018-02-05 at 21 50 26
screen shot 2018-02-05 at 21 56 52

- As an added bonus we have the new matplotlib color schemes

Viridis
screen shot 2018-02-05 at 21 01 30
Magma
screen shot 2018-02-05 at 21 01 49
Inferno
screen shot 2018-02-05 at 21 56 01
Plasma
screen shot 2018-02-05 at 21 56 19

Some points up for discussion @SylvainCorlay @dmadeka @ssunkara1 :
- more than just a `mid`, we can now pass as many values as there are `colors`, so we could think of how to handle that.
- we don't need the `divergent` attribute anymore

### CODE REVIEW

**Comment by dmadeka** [comment]
💯 🥇 👍

**Comment by rmenegaux** [comment]
The `mid` attribute now works as before, this is ready to be looked at, please test

**Comment by ssunkara1** [comment]
@rmenegaux This looks awesome!! Testing it out

**Comment by SylvainCorlay** [comment]
Reviewed in person with @rmenegaux merging WOOOOT!

**Pull request merged**
