### PR TITLE
Make bqplot work in JupyterLab

### PR DESCRIPTION
**Pull request by jasongrout**
Likely we'll need to first release a new version of ipywidgets, and then merge this depending on ipywidgets 6.x.

### CODE REVIEW

**Comment by jasongrout** [comment]
Initial success!
screen shot 2016-09-16 at 11 31 47 pm

**Comment by SylvainCorlay** [comment]
Ping @rmenegaux @dmadeka @ChakriCherukuri @ssunkara1. Check that out!

This is is simply awesome.

bqlab

**Comment by jasongrout** [comment]
@dmadeka, @SylvainCorlay - I just updated this to work with the latest jlab changes, but it seems that there are some conflicts. There might also be some other changes in Sylvain's similar PR.

**Comment by SylvainCorlay** [comment]
@jasongrout my other PR also has the same changes.

**Comment by jasongrout** [comment]
Superseded by #336.

**Pull request closed without merging**
