### PR TITLE
(WIP) Enable 'y' selection for BrushIntervalSelector

### PR DESCRIPTION
**Pull request by rmenegaux**
`BrushIntervalSelector` can be used vertically, by setting its `orientation` attribute to 'vertical'

Addresses issue #616

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Nice, I'll give it a try next week!

**Comment by SylvainCorlay** [comment]
Great!

**Comment by SylvainCorlay** [comment]
Awesome!

**Comment by maartenbreddels** [comment]
Works as expected, nice!

**Comment by SylvainCorlay** [comment]
Closing as included into https://github.com/bloomberg/bqplot/pull/634

**Pull request closed without merging**
