### PR TITLE
WIP Revert "Fix bqplot layout issues"

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Reverts bloomberg/bqplot#131

### CODE REVIEW

**Comment by dmadeka** [comment]
Looks like this undoes all the changes, why a WIP? I think this is pretty important and we should merge quickly

**Comment by SylvainCorlay** [comment]
Because I was trying to find a way to not resort to this.

**Comment by dmadeka** [comment]
Im good to merge this @SylvainCorlay, unless you have a better idea? It fixes #154 quickly

**Comment by SylvainCorlay** [comment]
OK, go ahead, I will reopen a PR adding the feature, hopefully without the issue. (I am also waiting for https://github.com/ipython/ipywidgets/pull/627) which will make it easier.

**Pull request merged**
