### PR TITLE
Figure: better DOM structure

### PR DESCRIPTION
**Pull request by maartenbreddels**
This DOM-structure fixes most of the issues in #782. Instead of having a separate interaction layer, there is a special background layer for the axes/ticks/background. This is needed to draw interactions on top of (webgl) canvas, but axes etc behind.
TODO:
 * [x] export/collapse svg
 * [x] tests

### CODE REVIEW

**Comment by maartenbreddels** [comment]
@ChakriCherukuri 
I'll continue after the weekend with the SVG and tests, then we should be able to merge this.

**Comment by maartenbreddels** [comment]
Not sure why travis didn't run, but this should fix the MarketMap.

**Comment by SylvainCorlay** [comment]
We reviewed this in person with @JohanMabille and @maartenbreddels and we think this is the way to go.

**Comment by SylvainCorlay** [comment]
This needs a rebase though.

**Comment by martinRenou** [comment]
It seems like it does not work as before
marketmap
The tooltip is completely black, and click events are not handled correctly. I'll try to find why

**Comment by martinRenou** [comment]
Do you mind it I fix it now on this PR? It does not look complicated

**Comment by maartenbreddels** [comment]
Please do! 👍

**Comment by martinRenou** [comment]
Fixed!
marketmapfixed

**Comment by maartenbreddels** [comment]
Awesome work!

**Comment by ChakriCherukuri** [comment]
@martinRenou @maartenbreddels can you please fix the conflicts. I'll merge it

**Comment by SylvainCorlay** [comment]
I rebased the PR. Testing locally and waiting for the tests to pass.

**Comment by maartenbreddels** [comment]
The test may fail, it may need to be rebased on #854

**Comment by SylvainCorlay** [comment]
Re-rebased the PR.

**Pull request merged**
