### PR TITLE
Race condition in the Image

### PR DESCRIPTION
**Pull request by rmenegaux**
The Image was sometimes not rescaling at all (some kind of a race condition). This cleans up and fixes that issue.
Animation is an added bonus.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
That may solve a mysterious bug I've seen where the image indeed doesn't respect the scales. 👍

**Comment by SylvainCorlay** [comment]
@rmenegaux I opened a PR to your branch fixing the race condition for the size of the figure.

**Comment by SylvainCorlay** [comment]
Can you confirm everything is fine for you. The race condition occurred very rarely even before the fix.

**Comment by rmenegaux** [comment]
Yes this fixes the race condition. This is ready to merge now

**Pull request merged**
