### PR TITLE
Traittypes dataframe

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Migrate to a traittypes implementation of a `DataFrame` trait.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@ssunkara1 let me know what you think. This is pretty much ready to go.

**Comment by SylvainCorlay** [comment]
:shipit:

**Comment by SylvainCorlay** [comment]
:shipit:

**Comment by dmadeka** [comment]
I test and merge this today, but you gotta get a few gifs please?

**Comment by SylvainCorlay** [comment]
Gif for the elections?

**Comment by dmadeka** [comment]
@maartenbredels Suggested we use gifs instead of pictures in the wiki to display the dynamic aspects of bqplot.. The elections in the README would be nice, but I wanted to add a non-parametric regression and we can control the order/bandwidth with sliders, but I think he meant more the communication between JavaScript/Python

**Comment by SylvainCorlay** [comment]
:shipit:

**Pull request merged**
