### PR TITLE
Tooltips

### LINKED ISSUE #85: tooltips don't automatically adjust position when they go off the edge of the screen
It's relatively straightforward to check positioning of the tooltip to make sure it's visible.  We should do this.

### PR DESCRIPTION
**Pull request by jasongrout**
Uses the Popper.js library to calculate tooltip position.

Fixes #85

### CODE REVIEW

**Comment by ssunkara1** [comment]
@jasongrout This does look very promising! :)

**Comment by jasongrout** [comment]
@dmadeka, @ssunkara1 - ready for review, I think.

**Comment by jasongrout** [comment]
@Fezvrasta - just curious, how did you find out we were using Popper.js?

**Comment by FezVrasta** [comment]
@jasongrout I monitor all the new GitHub issues that reference the word "popper" 😉

**Comment by dmadeka** [comment]
@jasongrout How does one do the install? If you change the require, Popper wont be installed by just pip install -e .

npm install failed, whats the other option?

**Comment by jasongrout** [comment]
@dmadeka - sorry, I forgot to commit a new file!

**Comment by dmadeka** [comment]
@jasongrout Two issues, the Tooltip is too close to the mouse and should have its corner to the mouse, not center I guess? Also, are you seeing your figure plus toolbar from plt.show become centered?

**Comment by jasongrout** [comment]
Right now, the tooltip snaps to the element the mouse is pointing at, not the mouse. There are options to offset it and put in an arrow.

Likely the figure+toolbar centering is fixed in https://github.com/jupyter-widgets/ipywidgets/pull/1547?

**Comment by jasongrout** [comment]
> @jasongrout Two issues, the Tooltip is too close to the mouse and should have its corner to the mouse, not center I guess?

The tooltip attempts to avoid the mouse, if possible. If there is not room for the tooltip to be to the side, it may overlap the mouse. Are you seeing the tooltip overlap the mouse where there is enough room for the tooltip to the side?

**Comment by FezVrasta** [comment]
If you want the tooltip to snap to the mouse you can pass a virtual reference element to Popper.js. It's described here:

https://popper.js.org/popper-documentation.html#referenceObject

**Comment by jasongrout** [comment]
@FezVrasta - thanks.

We already pass a virtual reference since we want the tooltip to snap to whatever element we are hovering over: https://github.com/bloomberg/bqplot/pull/516/files#diff-87e9791defd138cea2122bf31305a269R17. Basically, our virtual reference object lets us change the reference element dynamically.

**Comment by jasongrout** [comment]
@FezVrasta - we are seeing a weird flicker issue (basically, the tooltip flickers on and off once or twice on every mouse move, which is where we call for a scheduled update from popper) if the tooltip happens to be forced to overlap the reference element. I haven't tracked down whether that is in our code or popper's, but I'll let you know if it seems to be an issue in popper.

**Comment by ssunkara1** [comment]
@jasongrout The tooltip placement is not quite right for `Lines` and `Pie`. You can check them in the `Mark Interactions` example under Interactions in the example folder.

**Comment by jasongrout** [comment]
Great, thanks

**Comment by jasongrout** [comment]
> The tooltip placement is not quite right for Lines and Pie

The tooltip is placed right beside the object. Are you saying we should always follow the mouse position? The thing about the mouse position is that it often obscures the thing you are hovering over.

It's an easy change to follow the mouse pointer with an offset. Is that preferred? @dmadeka? @rmenegaux? @ssunkara1?

**Comment by ssunkara1** [comment]
@jasongrout I think following the mouse will be better.

**Comment by jasongrout** [comment]
I changed mark interactions to follow the mouse.

We still have an issue in those examples: when the interaction is changed to show the tooltip on click, I'm not sure how to get the event for closing the tooltip. The tooltip just stays up since we never close it. Thoughts?

**Comment by jasongrout** [comment]
(in particular, what event signifies that the tooltip should close when the tooltips are shown on mouse click?)

**Comment by ssunkara1** [comment]
@jasongrout For the `click` tooltip, we close it whenever there is the `background_click` event.

**Comment by jasongrout** [comment]
Actually, I just have code in the Mark.js `show_tooltip` and `hide_tooltip`. Is `hide_tooltip` not called whenever the tooltip needs to disappear, regardless of the event triggering the hide? It appears that `hide_tooltip` is not called when a background click is supposed to close the mark tooltip.

**Comment by ssunkara1** [comment]
which `Mark` are you looking at? In the function `process_interactions`, we do have that for the event `event_listeners.parent_clicked` for `Lines`, `Bars` `Hist` etc..

**Comment by stonebig** [comment]
any hope of quick resolution ?

**Comment by jasongrout** [comment]
@ssunkara1 - what do you think of the PR now? I updated it to work with the ipywidgets 7.0 release.

**Comment by jasongrout** [comment]
or @stonebig - can you test this PR?

**Comment by stonebig** [comment]
it doesn't seem to work any better, but it may be:
- my fault/bad setup,
- a side-effect of ipyleaflet or other,
- a bqplot detail that is managed well only in anaconda / linux.

**Comment by stonebig** [comment]
I get a message in javascript console:
````
lab:1 Uncaught (in promise) Module bqplot, semver range ^0.3.0-alpha.6 is not registered as a widget module
````

**Pull request merged**
