### PR TITLE
Added Wealth of Nations example

### PR DESCRIPTION
**Pull request by dmadeka**
@SylvainCorlay @stonebig This is in reference to #151 . A recreation of Mike Bostock's [Wealth of Nations](https://bost.ocks.org/mike/nations/).

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@dmadeka awesome!

Can you post a screenshot in the PR?

To include this, we might need to elaborate on the source of the data.

**Comment by dmadeka** [comment]
image

**Comment by dmadeka** [comment]
@SylvainCorlay I updated the `LICENSE` file

**Comment by dmadeka** [comment]
To do:
- [ ] Add Label on bottom right corner of Figure ala d3 example
- [ ] Add line drawn on hovered point for the entire path of the country

**Comment by stonebig** [comment]
Hi. I just tested:
- on chrome, it works, just:
   . didn't notice a mouse-over explanation of the bubble,
   . the automatic animation is slow and showing only 1 every 7 years (maybe a bigger pc is needed to make it smooth ?)
   . using the bottom slider, the animation is looking much better !?!
- on firefox... basically firefox seems to lock-up, doesn't work (or dead slow ?).

By Order of priority:
- I would like to get the mouse-over details, ("China", "USA", ...)
- is there something to improve the automatic experience ? if it can work great manually, the automation should not feel bad.

**Comment by dmadeka** [comment]
@stonebig Please look at #142 . This is being fixed but the `Tooltip` displays on the bottom left of the Figure for right now. You can change the animation speed by changing the sleep time in the `for` loop.

**Comment by dmadeka** [comment]
About the automatic animation, it seems its hard to get the `sleep` to work with the `animation_duration` attribute of the `Figure`. We are trying to resolve this right now, but the `IntSlider` is the way to make it smooth.

**Comment by dmadeka** [comment]
For Firefox please see #149

**Comment by stonebig** [comment]
I don't see any tooltip appring on the bottom left, let suppose this is my screen size, and anyway being fiexed.

**Comment by dmadeka** [comment]
@rmenegaux If you think its good, let's merge this?

**Comment by dmadeka** [comment]
@rmenegaux ping

**Comment by dmadeka** [comment]
@rmenegaux Rebased

**Comment by dmadeka** [comment]
Fixed the commit history and update the doc

@rmenegaux

**Comment by SylvainCorlay** [comment]
Related to this is this new PR upstream to improve the play button mechanism. https://github.com/ipython/ipywidgets/pull/633

**Comment by stonebig** [comment]
a stable beta would have been nice, tonight.

**Pull request merged**
