### PR TITLE
Add notebooks saved with widgets

### PR DESCRIPTION
**Pull request by kdheepak**
I reran all the notebook and committed them again. This will show all the plots in the notebooks on nbviewer.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Fantastic! Thanks for going through all the notebooks. Merging!

**Comment by kdheepak** [comment]
Thanks! However, there were a couple of issues with [this notebook](https://github.com/bloomberg/bqplot/blob/master/examples/Applications/Visualizing%20the%20US%20Elections.ipynb), one of which I wasn't able to figure out. That notebook has been left unchanged.

**Comment by SylvainCorlay** [comment]
Thanks. I suspect there is an issue with missing default values. I will look into it.

**Comment by dmadeka** [comment]
@kdheepak For Introduction.ipynb, you saved the notebook after panning actually. Should I go through the examples and make sure interactions weren't made or do you want to take care of that?

**Comment by kdheepak** [comment]
@dmadeka Sorry for the late reply, you can go ahead and take this.

**Pull request merged**
