### PR TITLE
Network

### PR DESCRIPTION
**Pull request by ChakriCherukuri**
First commit of graphs (there's lot more to be done. I'll do them one at a time)

### CODE REVIEW

**Comment by dmadeka** [comment]
@ChakriCherukuri This is a big PR. Im not sure about multiple small ones. How about we keep adding to this? Currently what does the syntax look like? You pass names and an adjacency matrix?

**Comment by dmadeka** [comment]
@ChakriCherukuri Also, should it use the Scatter for the points to enable interactivity and coloring? Or should it build its own interactivity? Or should it go the route of the HeatMap and allow large plots through canvas?

**Comment by ChakriCherukuri** [comment]
@ssunkara1, @dmadeka can you please review. Made graph a mark.
Will submit more changes in a separate PR

**Comment by ChakriCherukuri** [comment]
closing this PR. I will open one more with latest changes

**Pull request closed without merging**
