### PR TITLE
Set element

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This comes on the top of #258 . closes #258

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
In short, backbone's `view.el` should be a native DOM element.

Now in the views for figures, axes, marks and interactions, we correctly call backbone's setElement in initialize. The `d3el` attribute is a d3 selection on the `el` attribute.

This change cleans up our use of backbone and will be required for ipywidgets 6.0.

**Comment by dmadeka** [comment]
Probably shouldnt depend on #258

**Comment by SylvainCorlay** [comment]
Well it is related. How do we deal with the top element of the view, usage
of native browser api...

On Aug 9, 2016 4:23 PM, "Dhruv Madeka" <notifications@github.com> wrote:

Probably shouldnt depend on #258
<https://github.com/bloomberg/bqplot/pull/258>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bloomberg/bqplot/pull/262#issuecomment-238568957>, or mute
the thread

**Comment by dmadeka** [comment]
Oops, sorry, I meant the last commit shouldnt depend on any of it, this is good to depend on #258

**Comment by SylvainCorlay** [comment]
Ah ok :) I guess that if you merge it does not matter anymore :)

**Comment by SylvainCorlay** [comment]
:shipit:

**Comment by dmadeka** [comment]
testing

**Comment by SylvainCorlay** [comment]
Tested ?

**Comment by dmadeka** [comment]
Yes, Im getting an error in the Introduction notebook:

```
Error setting state: Cannot read property 'select' of undefinedBackbone.Model.extend.set_state @ widget.js:172(anonymous function) @ widget.js:151Promise.resolve (async)resolvePromisesDict @ utils.js:121Backbone.Model.extend._deserialize_state @ widget.js:437(anonymous function) @ widget.js:149Promise.resolve (async)Backbone.Model.extend._handle_comm_msg @ widget.js:142Comm._callback @ main.min.js:22109Comm.handle_msg @ main.min.js:22117(anonymous function) @ main.min.js:22045Promise.resolve (async)CommManager.comm_msg @ main.min.js:22043x.isFunction.i @ main.min.js:87Kernel._handle_iopub_message @ main.min.js:23338Kernel._finish_ws_message @ main.min.js:23175(anonymous function) @ main.min.js:23166Promise.resolve (async)Kernel._handle_ws_message @ main.min.js:23164x.isFunction.i @ main.min.js:87
```

**Comment by dmadeka** [comment]
```
Figure.js:578 Uncaught (in promise) TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.(…)(anonymous function) @ Figure.js:578Promise.resolve (async)(anonymous function) @ utils.js:98Promise.resolve (async)success_callback @ utils.js:78context.execCb @ require.js:1690Module.check @ require.js:865Module.enable @ require.js:1177Module.init @ require.js:783(anonymous function) @ require.js:1453setTimeout (async)(anonymous function) @ require.js:1809localRequire @ require.js:1442requirejs @ require.js:1791(anonymous function) @ utils.js:81(anonymous function) @ utils.js:76loadClass @ utils.js:66(anonymous function) @ manager-base.js:96Promise.resolve (async)ManagerBase.create_view @ manager-base.js:94WidgetViewMixin.create_child_view @ widget.js:496(anonymous function) @ Figure.js:573
```

**Comment by dmadeka** [comment]
Also, there's no Play in ipywidgets?

**Comment by SylvainCorlay** [comment]
OK, these errors also occur in master but I corrected some of it. I can't reproduce the one of your second comment. Which example is it?

**Comment by SylvainCorlay** [comment]
@dmadeka this should be good.

**Comment by SylvainCorlay** [comment]
@dmadeka I made some additional cleanup of `view.remove`. A lot of it was unnecessary.

**Comment by SylvainCorlay** [comment]
:shipit:

**Comment by dmadeka** [comment]
In `Introduction.ipynb` I get:

```
:8888/nbextensions/jupyter-js-widgets/extension.js?v=20160815215936:16516 Error setting state: Cannot read property 'scale' of undefined
```

**Comment by dmadeka** [comment]
Does it work if we change scales?

**Comment by dmadeka** [comment]
All else looks good @SylvainCorlay

**Comment by SylvainCorlay** [comment]
@dmadeka the scales error exists in master and is unrelated.

**Comment by SylvainCorlay** [comment]
This change is not small but quite mechanical. I don't think that there is much interest to wait any more.

**Comment by dmadeka** [comment]
Okay, let's do it

**Pull request merged**
