### PR TITLE
Fix simple typo: resepect -> respect

### LINKED ISSUE #986: Fix simple typo: resepect -> respect
There is a small typo in bqplot/axes.py.
Should read respect rather than resepect.

### PR DESCRIPTION
**Pull request by timgates42**
Closes #986

### CODE REVIEW

**Comment by martinRenou** [comment]
@timgates42 would you mind to commit with the `--signoff` option? `git commit --amend --signoff && git push -f origin bugfix/typo_respect` should do it :)

**Comment by timgates42** [comment]
Oh cool, never tried that before, will give it a go -Thanks!

**Comment by timgates42** [comment]
Ok thanks @martinRenou  Signed Off as my own work respecting the Open Source Apache License of the project.

**Comment by SylvainCorlay** [comment]
Thanks @timgates42! Merging.

**Pull request merged**
