### PR TITLE
Fix dark theme for bqplot

### PR DESCRIPTION
**Pull request by SylvainCorlay**
dark

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@dmadeka I am iterating on this since the dark theme is broken at the moment. Will cut a 0.7.2 shortly so merging.

**Comment by dmadeka** [comment]
Wait, we should be careful before cutting a release

**Comment by dmadeka** [comment]
Are we sure we don't want white axes?

**Comment by dmadeka** [comment]
The ticks are not very visible in this theme now

**Pull request merged**
