### PR TITLE
Changing the json format of date objects

### PR DESCRIPTION
**Pull request by ssunkara1**

### CODE REVIEW

**Comment by ssunkara1** [comment]
@SylvainCorlay Need help similar to #187. With `numpy >= 1.11.1` and `python >= 3.0` the `BrushSelector` should work as expected.

**Comment by SylvainCorlay** [comment]
@ssunkara1 you have tabs in your python code that prevent this to work on python 3.

**Comment by ssunkara1** [comment]
@SylvainCorlay Does it look better now?

**Comment by SylvainCorlay** [comment]
Yes, merging.

**Pull request merged**
